### ISSUE TITLE
Failed opening 'filename' (could not find 'fmt' in RIFF header)

### ISSUE THREAD

**Issue by pavlos163** [aubio/aubio#111]
Hi there,

I just cloned the aubio git repository to try the different onset and pitch detection techniques on some of my own recordings. I am using the python library.

However, on [this](http://vocaroo.com/i/s0KAABqsiBtB) audio file (and on any other audio file I have tried), I get the following error:

```
(aubio) pavlos55@pavlos55-SATELLITE-S50-B:~/aubio/python/demos$ python demo_onset_plot.py 3stSTRING.WAV 
Traceback (most recent call last):
  File "demo_onset_plot.py", line 19, in <module>
    s = source(filename, samplerate, hop_s)
RuntimeError: AUBIO ERROR: source_wavread: Failed opening 3stSTRING.WAV (could not find 'fmt ' in RIFF header)

```

I have also tried with Python3 with no success.

**Comment by piem** [comment]
hi @pk1914 

what platform are you running aubio on? did you check that you could read the file? if you compiled aubio without any external libraries, you will only be able to open very basic wav files.

ffmpeg which is one of the most complete ones, but libsndfile can read for most uncompressed formats. See https://aubio.org/manual/latest/installing.html#libav

To rebuild aubio with an additional library, you should be able to:
 - install chosen libraries (for instance ffmpeg, with header files)
 - rebuild and reinstall aubio
 - open `3stSTRING.WAV` and many more

**Comment by pk1914** [comment]
Hi @piem 

I am running on Ubuntu 16.04. I installed aubio just with the `pip install aubio` command. I already have ffmpeg install on my computer. When I try `sudo apt-get install ffmpeg` I get:

`0 to upgrade, 0 to newly install, 0 to remove and 17 not to upgrade.`

**Comment by piem** [comment]
you can try to make sure ffmpeg headers are installed, then re-install aubio:

    sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev libswresample-dev
    pip uninstall -yv aubio
    pip install --force-reinstall --no-cache-dir --verbose aubio

**Comment by pk1914** [comment]
Unfortunately, after these commands I still get the same error.

During `sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev libswresample-dev` I got some of these messages:

`N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension` 

I don't know if it's relevant but thought I should still put it here.

**Comment by pk1914** [comment]
Actually, after the `pip install` command I got:

```
    Package aubio was not found in the pkg-config search path.
    Perhaps you should add the directory containing `aubio.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'aubio' found
    Running "pkg-config --libs --cflags aubio = 0.4.5" failed: CalledProcessError()
    Info: aubio 0.4.5 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    checking for libavformat
    checking for libavutil
    checking for libswresample
    checking for libavresample
    Package libavresample was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libavresample.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libavresample' found
    Running "pkg-config --libs --cflags libavresample" failed: CalledProcessError()
    checking for sndfile
    checking for samplerate
    Package samplerate was not found in the pkg-config search path.
    Perhaps you should add the directory containing `samplerate.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'samplerate' found
    Running "pkg-config --libs --cflags samplerate" failed: CalledProcessError()
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: x86_64-linux-gnu-gcc -pthread -E -DAUBIO_UNSTABLE=1 -Isrc src/aubio.h

```

**Comment by piem** [comment]
Ok, so it seems libav* are correctly detected. What do the following lines look like? Do they include `-DHAVE_LIBAV=1`? Mine look like this:

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DAUBIO_VERSION=0.4.5 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_SWRESAMPLE=1 -DHAVE_LIBAV=1 -DHAVE_SNDFILE=1 -DHAVE_SAMPLERATE=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -I/home/piem/projects/aubio/aubiopyenv3/lib/python3.4/site-packages/numpy/core/include -Isrc -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -Ipython/gen -I/usr/include/python3.4m -I/home/piem/projects/aubio/aubiopyenv3/include/python3.4m -c python/ext/aubiomodule.c -o build/temp.linux-x86_64-3.4/python/ext/aubiomodule.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DAUBIO_VERSION=0.4.5 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_SWRESAMPLE=1 -DHAVE_LIBAV=1 -DHAVE_SNDFILE=1 -DHAVE_SAMPLERATE=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -I/home/piem/projects/aubio/aubiopyenv3/lib/python3.4/site-packages/numpy/core/include -Isrc -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -Ipython/gen -I/usr/include/python3.4m -I/home/piem/projects/aubio/aubiopyenv3/include/python3.4m -c python/ext/aubioproxy.c -o build/temp.linux-x86_64-3.4/python/ext/aubioproxy.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DAUBIO_VERSION=0.4.5 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_SWRESAMPLE=1 -DHAVE_LIBAV=1 -DHAVE_SNDFILE=1 -DHAVE_SAMPLERATE=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -I/home/piem/projects/aubio/aubiopyenv3/lib/python3.4/site-packages/numpy/core/include -Isrc -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -Ipython/gen -I/usr/include/python3.4m -I/home/piem/projects/aubio/aubiopyenv3/include/python3.4m -c python/ext/py-cvec.c -o build/temp.linux-x86_64-3.4/python/ext/py-cvec.o
x86_64-linux-gnu-gcc [...]
```

**Comment by pk1914** [comment]
Mine look like this:

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DAUBIO_VERSION=0.4.5 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_SNDFILE=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -I/home/pavlos55/guitartab/.env/local/lib/python2.7/site-packages/numpy/core/include -Isrc -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/local/include -Ipython/gen -I/usr/include/python2.7 -c python/ext/aubiomodule.c -o build/temp.linux-x86_64-2.7/python/ext/aubiomodule.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DAUBIO_VERSION=0.4.5 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_SNDFILE=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -I/home/pavlos55/guitartab/.env/local/lib/python2.7/site-packages/numpy/core/include -Isrc -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/local/include -Ipython/gen -I/usr/include/python2.7 -c python/ext/aubioproxy.c -o build/temp.linux-x86_64-2.7/python/ext/aubioproxy.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DAUBIO_VERSION=0.4.5 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_SNDFILE=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -I/home/pavlos55/guitartab/.env/local/lib/python2.7/site-packages/numpy/core/include -Isrc -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/local/include -Ipython/gen -I/usr/include/python2.7 -c python/ext/py-cvec.c -o build/temp.linux-x86_64-2.7/python/ext/py-cvec.o

```

**Comment by piem** [comment]
So libsndfile is detected and should be used, but something is wrong with ffmpeg detection: it seems to find all the libs, except libavresample which is deprecated now in favor of libswresample, but it's not being used. So I'm not sure what's missing.

To make sure: did you double check `3stSTRING.WAV` is a valid file? aubio should be able to read it with libsndfile. does `sndfile-info` have something special to say about it?

**Comment by pk1914** [comment]
Yes, it is a valid file.

This is what `sndfile-info` outputs:

```
File : static/3stSTRING.wav
Length : 9432576
RIFF : 9432568
WAVE
bext : 858
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 4
  Bit Width     : 16
  Bytes/sec     : 176400
PAD  : 31850
data : 9399808
End

----------------------------------------
Sample Rate : 44100
Frames      : 2349952
Channels    : 2
Format      : 0x00010002
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:53.287
Signal Max  : 16529 (-5.94 dB)

```

**Comment by pk1914** [comment]
By the way, this happened every time I tried, also with .mp3 files and with .wav files from other sources. So the issue is in my setup or PC, not the file.

Any other ideas?

This is my code:

```
def transcribe(filename):
  sr = 40000

  win_s = 512
  hop_s = win_s // 2

  s = source(filename, sr, hop_s)
  o = onset("default", win_s, hop_s, sr)

  onsets = []

  total_frames = 0
  while True:
    samples, read = s()
    if o(samples):
      onsets.append(o.get_last())
    total_frames += read
    if read < hop_s: break

  print onsets
```

And this all runs in a Flask server. The file is uploaded to the server before handled by this code.

**Comment by piem** [comment]
Your code looks fine, except that it is using an unusual sample rate. Can you run `aubio onset 3stSTRING.WAV` ?

About the flask server, we are interested in this too. See also notes by @danielweinmann in #104.

**Comment by pk1914** [comment]
`aubio onset` from the command-line worked:

```
(.env) pavlos55@pavlos55-SATELLITE-S50-B:~/guitartab/guitartab$ aubio onset static/Guitar\ Samples/3st\ STRING.WAV 
0.139819	
0.158413	
0.366893	
0.397914	
0.514014	
0.803900	
1.364558	
2.662290	
2.702880	
...
53.237664	
```

**Comment by piem** [comment]
So aubio seems to run fine there. Could it be that your flask server is running in a different python environment?

**Comment by pk1914** [comment]
How can I check that? My server is running inside a `virtualenv`, could that mean anything?

**Comment by pk1914** [comment]
So, from the command-line, when I call `aubio onset` outside my `virtualenv`, it does not work. Inside my `virtualenv` it does (only for `.wav` files, not for `.mp3`).

So, outside the `venv`, I got:

```
pavlos55@pavlos55-SATELLITE-S50-B:~/guitartab/app$ aubio onset static/audio/Guitar\ Samples/3st\ STRING.WAV 
Traceback (most recent call last):
  File "/usr/local/bin/aubio", line 9, in <module>
    load_entry_point('aubio==0.4.6a0+b37e2b2.mods', 'console_scripts', 'aubio')()
  File "/usr/local/lib/python3.5/dist-packages/aubio/cmd.py", line 386, in main
    samplerate=args.samplerate) as a_source:
RuntimeError: AUBIO ERROR: source_wavread: Failed opening static/audio/Guitar Samples/3st STRING.WAV (could not find 'fmt ' in RIFF header)
pavlos55@pavlos55-SATELLITE-S50-B:~/guitartab/app$ aubio onset static/audio/Guitar.ff.sulA.C4E4.mp3 
Traceback (most recent call last):
  File "/usr/local/bin/aubio", line 9, in <module>
    load_entry_point('aubio==0.4.6a0+b37e2b2.mods', 'console_scripts', 'aubio')()
  File "/usr/local/lib/python3.5/dist-packages/aubio/cmd.py", line 386, in main
    samplerate=args.samplerate) as a_source:
RuntimeError: AUBIO ERROR: source_wavread: Failed opening static/audio/Guitar.ff.sulA.C4E4.mp3 (could not find RIFF header)
```

But then inside it:

```
pavlos55@pavlos55-SATELLITE-S50-B:~/guitartab/app$ . ../.env/bin/activate
(.env) pavlos55@pavlos55-SATELLITE-S50-B:~/guitartab/app$ aubio onset static/audio/Guitar\ Samples/4st\ STRING.WAV 
0.148776	
...
53.357528	
(.env) pavlos55@pavlos55-SATELLITE-S50-B:~/guitartab/app$ aubio onset static/audio/Guitar.ff.sulA.C4E4.mp3 
Traceback (most recent call last):
  File "/home/pavlos55/guitartab/.env/bin/aubio", line 11, in <module>
    load_entry_point('aubio==0.4.5', 'console_scripts', 'aubio')()
  File "/home/pavlos55/guitartab/.env/local/lib/python2.7/site-packages/aubio/cmd.py", line 375, in main
    samplerate=args.samplerate) as a_source:
RuntimeError: AUBIO ERROR: source_wavread: Failed opening static/audio/Guitar.ff.sulA.C4E4.mp3 (could not find RIFF header)
```

**Comment by piem** [comment]
@pk1914 so it seems the one installed in your virtualenv was compiled with libsndfile, but not in `/usr/local`. I would suggest removing the one in `/usr/local`. Now we still need to figure out why ffmpeg is not detected correctly.

**Comment by piem** [comment]
hi @pk1914  have you made any progress on this?

cheers, piem

**Comment by brianc118** [comment]
@piem I'm getting the same error when installing inside virtualenv. It doesn't seem to be detecting ffmpeg?

**Comment by piem** [comment]
hi @brianc118 

great, thanks for the update! yes, you do need to install pkg-config.

best, piem
