### ISSUE TITLE
Can't import aubio on macos

### ISSUE THREAD

**Issue by jerryyip** [aubio/aubio#113]
This is what I got:
```
python -c "import aubio; print(aubio.version)"
/Library/Python/2.7/site-packages/aubio-0.4.6a0+b37e2b25-py2.7-macosx-10.12-intel.egg/aubio/_aubio.py:3: UserWarning: Module aubio was already imported from /Library/Python/2.7/site-packages/aubio-0.4.6a0+b37e2b25-py2.7-macosx-10.12-intel.egg/aubio/__init__.pyc, but /Users/jy/Documents/myGithub/aubio is being added to sys.path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.12-intel/egg/aubio/__init__.py", line 4, in <module>
  File "build/bdist.macosx-10.12-intel/egg/aubio/_aubio.py", line 7, in <module>
  File "build/bdist.macosx-10.12-intel/egg/aubio/_aubio.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/jy/Library/Caches/Python-Eggs/aubio-0.4.6a0+b37e2b25-py2.7-macosx-10.12-intel.egg-tmp/aubio/_aubio.so, 2): Library not loaded: /usr/local/lib/libaubio.5.dylib
  Referenced from: /Users/jy/Library/Caches/Python-Eggs/aubio-0.4.6a0+b37e2b25-py2.7-macosx-10.12-intel.egg-tmp/aubio/_aubio.so
  Reason: image not found
```

**Comment by piem** [comment]
hi @jerryyip 

how did you compile aubio? it seems you compiled it to link against libaubio, but did not install libaubio on your system. you could try `./waf install`, or `./waf distclean && pip install .`

let us know how it goes,

best, Paul

**Comment by jerryyip** [comment]
Hi @piem 
I tried `./waf install`, but still can't import aubio
And I tried `./waf distclean && sudo pip install .`,  just got an OSError:
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/aubio-0.4.6a0+b37e2b25-py2.7-macosx-10.12-intel.egg'
```
I am new to python, should I recompile aubio? Thanks.

**Comment by jerryyip** [comment]
Thanks very much!! @piem  It works now.
Feel free to close this issue.
Thanks again.

**Comment by piem** [comment]
excellent, thanks for your feedback @jerryyip
