### ISSUE TITLE
reading sample data already in memory

### ISSUE THREAD

**Issue by rghvdberg** [aubio/aubio#127]
Hi,
I'm (slowly) developing a lv2 beatslicer plugin and looking to implement aubio.
Is it possible to have `new_aubio_source` load sample data already load in memory.
I have a stereo wav sample loaded in a` vector<float>` (via libsndfile)

**Comment by piem** [comment]
hi @rghvdberg 

you could use [`aubio_sampler`](https://github.com/aubio/aubio/blob/sampler/src/synth/sampler.h) for that, which you will find in the `sampler` branch. As a bonus, your plug-in will get time-stretching and pitch-shifting effects (if you compile aubio against rubberband).

for a complete example of how to use the latest aubio_sampler, check out [`[aubiosampler~]` in the `sampler` branch of pd-aubio](https://github.com/aubio/pd-aubio/blob/sampler/src/aubiosampler~.c).

let us know how this works for you.

*Note*: this branch should be fairly stable now, but breaks the API, so we are waiting to find other things to break before merging it.

**Comment by piem** [comment]
Another option is to grab slices of hop_size elements at each iteration:

1. create a *fake* fvec
2. set its length to the desired hop_size
3. have its data point to the current reading pointer
4. increment this reading pointer at each step.

Something like this should do:

```C
fvec_t ftable;               // 1. create fvec without allocating it
intptr_t readptr = 0;
ftable.length = hop_size;    // 2. set ftable length

while (readptr < cpp_vector.size()) {
  // 3. set ftable.data to point to the current slice
  ftable.data = cpp_vector[readptr];

  // do something with &ftable...
  // e.g. aubio_onset_do(onset, &ftable, onset_out);

  // 4. increment read pointer
  readptr += hop_size;
}
```

**Comment by rghvdberg** [comment]
wow .. very impressive !!!
but will all this with stereo samples ?

**Comment by rghvdberg** [comment]
oops .. wrong button

**Comment by piem** [comment]
no multi-channel support yet, but we plan to add it.

for now, you could simply create 2 samplers, one for each channel.

**Comment by rghvdberg** [comment]
I'm trying it and get
```
/home/rob/projects/aubio_test/main.cpp:41:15: error: cannot convert ‘float’ to ‘smpl_t* {aka float*}’ in assignment
```

**Comment by rghvdberg** [comment]
oh it's probably
`ftable.data = &cpp_vector[readptr];`

**Comment by rghvdberg** [comment]
I've tried this ;
```
#include <iostream>
#include <sndfile.hh>
#include <aubio/aubio.h>
#include <vector>
#include <jack/jack.h>
using namespace std;

int main()
{
    // load sample
    std::vector<float> cpp_vector;
    SndfileHandle fileHandle ( "/home/rob/projects/aubio_test/sample.ogg", SFM_READ,  SF_FORMAT_WAV | SF_FORMAT_FLOAT, 1, 44100 );
    int size  = fileHandle.frames();

    if ( size == 0 )
    {
        // file doesn't exist or is of incompatible type, main handles the -1
        cout << "oops" << endl;
        return -1;
    }
    
    int channels   = fileHandle.channels();
    int samplerate = fileHandle.samplerate();
    cpp_vector.resize ( size*channels );
    fileHandle.read ( &cpp_vector.at ( 0 ), size * channels );
    
    std::cout << "Loaded a file with " << channels << " channels, and a samplerate of " <<
              samplerate << " with " << size << " samples, so its duration is " <<
              size / samplerate << " seconds long." << std::endl;
	      
    // aubio stuff
    int hop_size = 512;
    int win_s = 512;
    fvec_t ftable;               // 1. create fvec without allocating it
    intptr_t readptr = 0;
    ftable.length = hop_size;    // 2. set ftable length
    fvec_t * onset_out;
    fvec_t * out = new_fvec ( 2 ); // output position
    // create onset object
    aubio_onset_t * onset = new_aubio_onset ( "default", win_s, hop_size, samplerate );
    while ( readptr < cpp_vector.size() )
    {
        // 3. set ftable.data to point to the current slice
        ftable.data = &cpp_vector[readptr];
        // do something with &ftable...
        // e.g. aubio_onset_do(onset, &ftable, onset_out);
        aubio_onset_do ( onset , &ftable, onset_out );
        if ( out->data[0] != 0 )
        {
            cout << "onset at " << aubio_onset_get_last_ms ( onset ) << " ";
        }
        // 4. increment read pointer
        readptr += hop_size;
    }
    cout << endl;
    del_aubio_onset ( onset );
    //del_fvec ( ftable );
    del_fvec ( out );
    aubio_cleanup();
    return 0;
}
```
but I get a segfault :disappointed: 

```
0  aubio_peakpicker_do (p=0x8064088, onset=0x80642a0, out=0xffff) at ../src/onset/peakpicker.c:119
#1  0xb7f2500e in aubio_onset_do (o=0x8062750, input=0xbffff098, onset=0xffff) at ../src/onset/onset.c:71
#2  0x0804a881 in main () at /home/rob/projects/aubio_test/main.cpp:47
(gdb) thread apply all bt
``` 
line 47 is
`aubio_onset_do ( onset , &ftable, onset_out );`

**Comment by rghvdberg** [comment]
I think this works :+1: 
```
#include <iostream>
#include <sndfile.hh>
#include <aubio/aubio.h>
#include <vector>
#include <jack/jack.h>
using namespace std;

int main()
{
    // load sample
    std::vector<float> cpp_vector;
    SndfileHandle fileHandle ( "/home/rob/projects/aubio_test/sample.ogg", SFM_READ,  SF_FORMAT_WAV | SF_FORMAT_FLOAT, 1, 44100 );
    int size  = fileHandle.frames();

    if ( size == 0 )
    {
        // file doesn't exist or is of incompatible type, main handles the -1
        cout << "oops" << endl;
        return -1;
    }

    int channels   = fileHandle.channels();
    int samplerate = fileHandle.samplerate();
    cpp_vector.resize ( size*channels );
    fileHandle.read ( &cpp_vector.at ( 0 ), size * channels );

    std::cout << "Loaded a file with " << channels << " channels, and a samplerate of " <<
              samplerate << " with " << size << " samples, so its duration is " <<
              size / samplerate << " seconds long." << std::endl;

    // aubio stuff
    int hop_size = 512;
    int win_s = 512;
    fvec_t ftable;               // 1. create fvec without allocating it
    intptr_t readptr = 0;
    ftable.length = hop_size;    // 2. set ftable length
    fvec_t * out = new_fvec ( 2 ); // output position
    // create onset object
    aubio_onset_t  * onset = new_aubio_onset ( "default", win_s, hop_size, samplerate );
    while ( readptr < cpp_vector.size() )
    {
        // 3. set ftable.data to point to the current slice
        ftable.data = &cpp_vector[readptr];
        // do something with &ftable...
        // e.g. aubio_onset_do(onset, &ftable, onset_out);
        // cout << readptr << endl;
        aubio_onset_do ( onset , &ftable, out );
        if ( out->data[0] != 0 )
        {
            cout << "onset at " << aubio_onset_get_last_ms ( onset ) << endl;
        }
        // 4. increment read pointer
        readptr += hop_size;
    }
    cout << endl;
    del_aubio_onset ( onset );
    del_fvec ( &ftable );
    del_fvec ( out );
    aubio_cleanup();
    return 0;
}
```

**Comment by piem** [comment]
hello @rghvdberg 

excellent, thanks for the fixes!  i guess this issue could be closed now?

best, piem

**Comment by rghvdberg** [comment]
got it working :-)
a bit crude, but it works
https://github.com/rghvdberg/ninjas
closing this
many thanks for your help and awesome library!!

**Comment by piem** [comment]
excellent, thank you for the feedback @rghvdberg !
