### ISSUE TITLE
vamp-aubio-plugins: wscript does not recognize i686

### ISSUE THREAD

**Issue by deep-42-thought** [aubio/aubio#169]
**This report is for `https://aubio.org/pub/vamp-aubio-plugins/vamp-aubio-plugins-0.5.1.tar.bz2` - I didn't find a development version of that to check if the issue is fixed already.** Excuse me, if that's not the right place to report this bug.

`elif platform.machine() == 'x86_64':` on line 48 should be `elif platform.machine() == 'i686':`, otherwise compilation on i686 fails with
```
Setting top to                           : /build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1 
Setting out to                           : /build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Traceback (most recent call last):
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/waflib/Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/waflib/Scripting.py", line 175, in run_commands
    ctx=run_command(cmd_name)
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/waflib/Scripting.py", line 166, in run_command
    ctx.execute()
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/waflib/Configure.py", line 87, in execute
    super(ConfigurationContext,self).execute()
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/build/vamp-aubio-plugins/src/vamp-aubio-plugins-0.5.1/wscript", line 58, in configure
    local_vamp_stlib = os.path.join(local_vamp_lib, local_vamp_stlib)
UnboundLocalError: local variable 'local_vamp_lib' referenced before assignment
```

**Comment by piem** [comment]
hello,

Well, this message is misleading, but it seems waf was not able to  find your vamp installation.

Did you try the latest git version? Also, please make sure you look at the [README](https://github.com/aubio/vamp-aubio-plugins/blob/master/README.md#build-instructions) for building instructions.

There is a mirror of the git repo for [`vamp-aubio-plugins`](https://aubio.org/vamp-aubio-plugins/) on github:

> https://github.com/aubio/vamp-aubio-plugins

I'm closing this issue for now. Please provide us with more info here: [vamp-aubio-plugins#2](https://github.com/aubio/vamp-aubio-plugins/issues/2).

@deep-42-thought, we are all looking forward for your answer (to everything).
