### ISSUE TITLE
[windows] python installation issue

### ISSUE THREAD

**Issue by MaxHastings** [aubio/aubio#199]
I tried installing aubio using "python -m pip install aubio". I have Visual C++ 14.0 installed, and my setuptools is up to date. But I end up getting the following error every time. It seems like I am missing mspdbcore.dll but after googling I haven't figured out a way to fix it. Any help is greatly appreciated.

> Collecting aubio
  Using cached https://files.pythonhosted.org/packages/d3/b6/6e5c91ece3935f6f06e370580188c69d4bbb0b6682ff1ff2bcf6c02a41ab/aubio-0.4.6.tar.gz
Requirement already satisfied: numpy in c:\users\maxwell\appdata\local\programs\python\python36\lib\site-packages (from aubio) (1.15.1)
Installing collected packages: aubio
  Running setup.py install for aubio ... error
    Complete output from command C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Maxwell\\AppData\\Local\\Temp\\pip-install-sewdkwoi\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Maxwell\AppData\Local\Temp\pip-record-d7mnhbmo\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\aubio
    copying python\lib\aubio\cmd.py -> build\lib.win-amd64-3.6\aubio
    copying python\lib\aubio\cut.py -> build\lib.win-amd64-3.6\aubio
    copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-3.6\aubio
    copying python\lib\aubio\slicing.py -> build\lib.win-amd64-3.6\aubio
    copying python\lib\aubio\__init__.py -> build\lib.win-amd64-3.6\aubio
    running build_ext
    checking for aubio = 0.4.6
    Running "pkg-config --libs --cflags aubio = 0.4.6" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    Info: aubio 0.4.6 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libavformat
    Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libavutil
    Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libswresample
    Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libavresample
    Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for sndfile
    Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for samplerate
    Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe -E -x c -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Maxwell\AppData\Local\Temp\pip-install-sewdkwoi\aubio\setup.py", line 85, in <module>
        'tests': ['numpy'],
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Maxwell\AppData\Local\Temp\pip-install-sewdkwoi\aubio\python\lib\moresetuptools.py", line 192, in build_extension
        usedouble=enable_double)
      File "C:\Users\Maxwell\AppData\Local\Temp\pip-install-sewdkwoi\aubio\python\lib\gen_external.py", line 238, in generate_external
        c_declarations = get_c_declarations(header, usedouble=usedouble)
      File "C:\Users\Maxwell\AppData\Local\Temp\pip-install-sewdkwoi\aubio\python\lib\gen_external.py", line 108, in get_c_declarations
        raise Exception("preprocessor output is empty:\n%s" % err_output)
    Exception: preprocessor output is empty:
    b"Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26729 for x64\r\nCopyright (C) Microsoft Corporation.  All rights reserved.\r\n\r\ncl : Command line warning D9002 : ignoring unknown option '-x'\r\nc\r\nc1: fatal error C1356: unable to find mspdbcore.dll\r\naubio.h\r\nc1: fatal error C1356: unable to find mspdbcore.dll\r\n"

> Command "C:\Users\Maxwell\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Maxwell\\AppData\\Local\\Temp\\pip-install-sewdkwoi\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Maxwell\AppData\Local\Temp\pip-record-d7mnhbmo\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Maxwell\AppData\Local\Temp\pip-install-sewdkwoi\aubio\

**Comment by piem** [comment]
Hi @MaxHastings 

it seems your setup tools can not find the correct compiler.

Can you build another simpler package? You could try PyYAML for instance:

```
pip install --compile PyYAML --verbose --ignore-installed
```

Also, can you try upgrading pip and setup tools?

```
python -m pip install --verbose --upgrade pip
python -m pip install --verbose --upgrade wheel
python -m pip install --verbose --upgrade setuptools
```

cheers, piem

**Comment by hnsyprst** [comment]
Sorry to necro, but I've been having the same issue using VS Code on Windows 10. Following this guide solved the problem for me: https://code.visualstudio.com/docs/cpp/config-msvc

Hope this helps whoever else happens to struggle w this issue 5 years down the line!
