### ISSUE TITLE
pointer being freed was not allocated

### ISSUE THREAD

**Issue by OneDirection9** [aubio/aubio#207]
Hi,
    
When I run the code following with `aubio=0.4.8a0`:

```python
def melbands_aubio(input_file, samplerate=44100, win_size=1024, hop_size=512,
                   n_bands=40, as_librosa=True):
    src = aubio.source(input_file, samplerate, hop_size)
    pv = aubio.pvoc(win_size, hop_size)
    fb = aubio.filterbank(n_bands, win_size)
    if not as_librosa:
        fb.set_mel_coeffs_slaney(samplerate)
    else:  # librosa uses full range [0, fs/2]
        melfreqs = librosa.mel_frequencies(n_mels=n_bands + 2, fmax=samplerate / 2)
        fb.set_triangle_bands(aubio.fvec(melfreqs), samplerate)

    melbands = np.ndarray([0, n_bands])
    while True:
        samples, read = src()
        fftgrain = pv(samples)
        if as_librosa: fftgrain.norm **= 2.  # librosa take L2 of the norm
        bands = fb(fftgrain)
        melbands = np.vstack([melbands, bands])
        if read < hop_size: break

    return melbands.T
```

Following error occurred:
```
python(3872,0x10737a5c0) malloc: *** error for object 0xffc00000ffc00000: pointer being freed was not allocated
python(3872,0x10737a5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Here is the [example audio file](https://drive.google.com/file/d/1sNOheTceTuWpGHTbvvqbLpAQl46zjKCs/view?usp=sharing).

**Comment by OneDirection9** [comment]
When I set parameters as `win_size=1764` and `hop_size=882`, the error occurred.

**Comment by piem** [comment]
Hi @OneDirection9 

What operating system are you running? Which version of python?

I can't seem to reproduce this crash. Here is what I get when trying to create a pvoc with these sizes:

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aubio
>>> aubio.pvoc(1764, 882)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: AUBIO ERROR: fft: can only create with sizes power of two, requested 1764, try recompiling aubio with --enable-fftw3
```

Note there are several fft routines available. After recompiling libaubio to use fftw, I get instead:

```
>>> a = aubio.pvoc(1764, 882)
>>> a(aubio.fvec(882))
aubio cvec of 883 elements
```

cheers, piem

**Comment by OneDirection9** [comment]
Hi @piem ,

My python version is:
```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import aubio
>>> a = aubio.pvoc(1764, 882)
>>> a(aubio.fvec(882))
aubio cvec of 883 elements
```

But when I run the function `melbands_aubio`, It failed.

Could you run the code with a aubio file?

Thanks.

**Comment by OneDirection9** [comment]
I run the code two times consecutively, the output is:

```
 > python test.py 
/anaconda3/envs/cf_env/lib/python3.6/site-packages/numba/errors.py:102: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
aubio
[[0.07680172 0.05809696 0.2643277  ...        nan        nan        nan]
 [0.02002315 0.03887276 0.21845917 ...        nan        nan        nan]
 [0.01018016 0.02571083 0.20058295 ...        nan        nan        nan]
 ...
 [0.00123238 0.00170655 0.05355224 ...        nan        nan        nan]
 [0.00105348 0.00127258 0.05034614 ...        nan        nan        nan]
 [0.00165501 0.00136688 0.04745101 ...        nan        nan        nan]]

 > python test.py 
/anaconda3/envs/cf_env/lib/python3.6/site-packages/numba/errors.py:102: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
python(36805,0x1141d35c0) malloc: Incorrect checksum for freed object 0x7fe801356a00: probably modified after being freed.
Corrupt value: 0x51e7e394520c2f81
python(36805,0x1141d35c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by OneDirection9** [comment]
The `test.py` is:
```python
  1 import aubio, librosa
  2 
  3 def melbands_aubio(input_file, samplerate=44100, win_size=1024, hop_size=512,
  4                            n_bands=40, as_librosa=True):
  5     src = aubio.source(input_file, samplerate, hop_size)
  6     pv = aubio.pvoc(win_size, hop_size)
  7     fb = aubio.filterbank(n_bands, win_size)
  8     if not as_librosa:
  9         fb.set_mel_coeffs_slaney(samplerate)
 10     else:  # librosa uses full range [0, fs/2]
 11         melfreqs = librosa.mel_frequencies(n_mels=n_bands + 2, fmax=samplerate / 2)
 12         fb.set_triangle_bands(aubio.fvec(melfreqs), samplerate)
 13 
 14     melbands = np.ndarray([0, n_bands])
 15     while True:
 16         samples, read = src()
 17         fftgrain = pv(samples)
 18         if as_librosa: fftgrain.norm **= 2.  # librosa take L2 of the norm
 19         bands = fb(fftgrain)
 20         melbands = np.vstack([melbands, bands])
 21         if read < hop_size: break
 22 
 23     return melbands.T
 24 
 25 
 26 file = './bus01.wav'
 27 
 28 y = melbands_aubio(file, samplerate=44100, win_size=1764, hop_size=882)
 29 print(y)
```

I used to run on a Mac os system. And when I run on a linux system, the error same as yours occurred:

```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    y = melbands_aubio(file, samplerate=44100, win_size=1764, hop_size=882)
  File "test.py", line 6, in melbands_aubio
    pv = aubio.pvoc(win_size, hop_size)
RuntimeError: AUBIO ERROR: fft: can only create with sizes power of two, requested 1764, try recompiling aubio with --enable-fftw3
```

I just install `aubio` by `pip install aubio`, how to recompile it?

**Comment by OneDirection9** [comment]
I have passed all the test examples after re-install from source code.

```
Ran 556 tests in 0.497s

OK (skipped=28)
```

I don't find the document to re-compile it.

**Comment by piem** [comment]
To build against fftw3, you first need to have `libfftw3-dev` installed.

By default, the python build does not check for fftw3, but you can patch the python builder to do that and rerun `pip install -Iv .`:

```patch
diff --git a/python/lib/moresetuptools.py b/python/lib/moresetuptools.py
index 3fd4e74a..f9a39ced 100644
--- a/python/lib/moresetuptools.py
+++ b/python/lib/moresetuptools.py
@@ -79,7 +79,7 @@ def add_external_deps(ext, usedouble = False):
     packages = ['libavcodec', 'libavformat', 'libavutil',
                 'libswresample', 'libavresample',
                 'sndfile',
-                #'fftw3f',
+                'fftw3f',
                ]
     # samplerate only works with float
     if usedouble is False:
```

Another option is to build and install libaubio first, using `./waf configure --enable-fftw3`, then rebuild python-aubio module to have it link against libaubio.

Links to documentation:
 - [building aubio python module](https://aubio.org/manual/latest/python_module.html)
 - [building libaubio](https://aubio.org/manual/latest/installing.html)

But this is a different issue :)

We are still trying to identify the crash on darwin. Can you find where in the script the crash occurs?

**Comment by OneDirection9** [comment]
Hi **@piem **

After re-compile it with `fftw3f` and run it on the linux system. It worked.
So I will close this issue.

Thanks.

**Comment by piem** [comment]
@OneDirection9 great you got it working.

But we are still trying to identify why the crash on macOS. Can you spot which line is crashing? Are you sure you are using the version from `master`, and not `0.4.7`?

**Comment by OneDirection9** [comment]
Hi, **@piem** 

the version is `0.4.8a0+9ef3c6e.mods`. I just clone the repository and uncomment `#'fftw3f',` in `/python/lib/moresetuptools.py`.

I also try to find which line is crashing. After I add some `print` functions, I find that it will crashed in the loop:

```python
def melbands_aubio(input_file, samplerate=44100, win_size=1024, hop_size=512,
                   n_bands=40, as_librosa=True):
    src = aubio.source(input_file, samplerate, hop_size)
    pv = aubio.pvoc(win_size, hop_size)
    fb = aubio.filterbank(n_bands, win_size)
    print('after pv,fb')
    if not as_librosa:
        fb.set_mel_coeffs_slaney(samplerate)
    else:  # librosa uses full range [0, fs/2]
        melfreqs = librosa.mel_frequencies(n_mels=n_bands + 2, fmax=samplerate / 2)
        fb.set_triangle_bands(aubio.fvec(melfreqs), samplerate)
    print('start calculate')
    melbands = np.ndarray([0, n_bands])
    while True:
        print('**************    start loop')
        samples, read = src()
        print(read)
        print('before pv')
        fftgrain = pv(samples)
        print('after pv')
        if as_librosa: fftgrain.norm **= 2.  # librosa take L2 of the norm
        bands = fb(fftgrain)
        print('after fb')
        print(bands)
        melbands = np.vstack([melbands, bands])
        print('before if')
        if read < hop_size: break

    return melbands.T
```

the output is:
```
**************    start loop
882
before pv
after pv
after fb
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan]
before if
......
**************    start loop
882
before pv
after pv
after fb
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan]
before if
**************    start loop
0
before pv
after pv
after fb
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan]
before if
python(48907,0x11ec585c0) malloc: Incorrect checksum for freed object 0x7fc03fba4200: probably modified after being freed.
Corrupt value: 0xffc00000ffc00000
python(48907,0x11ec585c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by piem** [comment]
Ok, i could reproduce now.

It seems that vDSP/Accelerate computations are wrong for non-power of two sizes.

Will investigate, thanks for your report.

**Comment by piem** [comment]
hi @OneDirection9 

It turns out vDSP only supports sizes `r * 2 ** n`, where `n > 4` and `r` in `[1, 3, 5, 15]`. This is fixed in master now. Thanks for the report.

**Comment by OneDirection9** [comment]
Thanks, 
    
I will use the closest pow of two.
