### ISSUE TITLE
Error with pip install

### ISSUE THREAD

**Issue by baozix** [aubio/aubio#208]
$ pip install aubio --user
Collecting aubio
  Using cached https://files.pythonhosted.org/packages/f5/fe/94ef8f547835bcdb8a8ce66a8acd590b114be7f907861678adb1f4b190f6/aubio-0.4.7.tar.gz
Requirement already satisfied: numpy in c:\users\brent\pycharmprojects\test\venv\lib\site-packages (from aubio) (1.15.4)
Building wheels for collected packages: aubio
  Running setup.py bdist_wheel for aubio ... error
  Complete output from command c:\users\brent\pycharmprojects\test\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Brent\\AppData\\Local\\Temp\\pip-install-rkgact42\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Brent\AppData\Local\Temp\pip-wheel-7v1p95ru --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\cmd.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\cut.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\slicing.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\__init__.py -> build\lib.win-amd64-3.7\aubio
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\setup.py", line 85, in <module>
      'tests': ['numpy'],
    File "c:\users\brent\pycharmprojects\test\venv\lib\site-packages\setuptools\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\brent\pycharmprojects\test\venv\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\python\lib\moresetuptools.py", line 192, in build_extension
      usedouble=enable_double)
    File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\python\lib\gen_external.py", line 241, in generate_external
      c_declarations = get_c_declarations(header, usedouble=usedouble)
    File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\python\lib\gen_external.py", line 109, in get_c_declarations
      raise Exception("preprocessor output is empty:\n%s" % err_output)
  Exception: preprocessor output is empty:
  b'Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27023.1 for x64\r\nCopyright (C) Microsoft Corporation.  All rights reserved.\r\n\r\naubio.h\r\nc1: fatal error C1356: unable to find mspdbcore.dll\r\n'
  checking for aubio = 0.4.7
  Running "pkg-config --libs --cflags aubio = 0.4.7" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  Info: aubio 0.4.7 was not found by pkg-config
  Info: looking for *optional* additional packages
  checking for libavcodec
  Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  checking for libavformat
  Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  checking for libavutil
  Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  checking for libswresample
  Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  checking for libavresample
  Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  checking for sndfile
  Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  checking for samplerate
  Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
  Info: libaubio was not installed or built locally with waf, adding src/
  Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h

  ----------------------------------------
  Failed building wheel for aubio
  Running setup.py clean for aubio
Failed to build aubio
Installing collected packages: aubio
  Running setup.py install for aubio ... error
    Complete output from command c:\users\brent\pycharmprojects\test\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Brent\\AppData\\Local\\Temp\\pip-install-rkgact42\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Brent\AppData\Local\Temp\pip-record-u_n10qho\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\brent\pycharmprojects\test\venv\include\site\python3.7\aubio --user --prefix=:
    running install
    running build
    running build_py
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\setup.py", line 85, in <module>
        'tests': ['numpy'],
      File "c:\users\brent\pycharmprojects\test\venv\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\brent\pycharmprojects\test\venv\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Brent\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\python\lib\moresetuptools.py", line 192, in build_extension
        usedouble=enable_double)
      File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\python\lib\gen_external.py", line 241, in generate_external
        c_declarations = get_c_declarations(header, usedouble=usedouble)
      File "C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\python\lib\gen_external.py", line 109, in get_c_declarations
        raise Exception("preprocessor output is empty:\n%s" % err_output)
    Exception: preprocessor output is empty:
    b'Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27023.1 for x64\r\nCopyright (C) Microsoft Corporation.  All rights reserved.\r\n\r\naubio.h\r\nc1: fatal error C1356: unable to find mspdbcore.dll\r\n'
    checking for aubio = 0.4.7
    Running "pkg-config --libs --cflags aubio = 0.4.7" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    Info: aubio 0.4.7 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libavformat
    Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libavutil
    Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libswresample
    Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for libavresample
    Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for sndfile
    Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    checking for samplerate
    Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h

    ----------------------------------------
Command "c:\users\brent\pycharmprojects\test\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Brent\\AppData\\Local\\Temp\\pip-install-rkgact42\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Brent\AppData\Local\Temp\pip-record-u_n10qho\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\brent\pycharmprojects\test\venv\include\site\python3.7\aubio --user --prefix=" failed with error code 1 in C:\Users\Brent\AppData\Local\Temp\pip-install-rkgact42\aubio\

I have tried running it using all the various sources for pip install. Regardless it does not work. Python is version 3.7.0.

**Comment by piem** [comment]
hi @baozix 

>  Exception: preprocessor output is empty:

I guess you shouldn't be using the community VS for py3.7. Does it help if you set your PATH first?

    SET PATH="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin";%PATH%

Also, making sure `setuptools` is up-to-date usually helps:

    pip install --upgrade setuptools 

cheers, piem

**Comment by piem** [comment]
The build should working without setting PATH now, thanks for your report.
