### ISSUE TITLE
Error while trying to install aubio

### ISSUE THREAD

**Issue by gabrielmonteiroflex** [aubio/aubio#247]
Hi, I am facing an error when I try to install aubio through pip

Can somebody help me, please?

```
> pip install aubio
Collecting aubio
  Using cached https://files.pythonhosted.org/packages/cd/80/302d89240603e5347c7f8026c8b02c59f8dfaec66c91a743d82de7c86006/aubio-0.4.9.tar.gz
Requirement already satisfied: numpy in c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages (from aubio) (1.16.3)
Building wheels for collected packages: aubio
  Building wheel for aubio (setup.py) ... error
  ERROR: Complete output from command 'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-install-es8ltb5c\\aubio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-wheel-uor_bb_m' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\cmd.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\cut.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\slicing.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\__init__.py -> build\lib.win-amd64-3.7\aubio
  running build_ext
  error: [WinError 2] O sistema não pode encontrar o arquivo especificado
  checking for aubio = 0.4.9
  Running "pkg-config --libs --cflags aubio = 0.4.9" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  Info: aubio 0.4.9 was not found by pkg-config
  Info: looking for *optional* additional packages
  checking for libavcodec
  Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libavformat
  Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libavutil
  Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libswresample
  Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libavresample
  Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for sndfile
  Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for samplerate
  Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  Info: libaubio was not installed or built locally with waf, adding src/
  Running command: cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
  ----------------------------------------

>   ERROR: Failed building wheel for aubio
  Running setup.py clean for aubio
Failed to build aubio
Installing collected packages: aubio
  Running setup.py install for aubio ... error
    ERROR: Complete output from command 'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-install-es8ltb5c\\aubio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-record-rje46fyw\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    running build_ext
    error: [WinError 2] O sistema não pode encontrar o arquivo especificado
    checking for aubio = 0.4.9
    Running "pkg-config --libs --cflags aubio = 0.4.9" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    Info: aubio 0.4.9 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libavformat
    Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libavutil
    Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libswresample
    Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libavresample
    Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for sndfile
    Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for samplerate
    Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
    ----------------------------------------

> ERROR: Command "'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-install-es8ltb5c\\aubio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-record-rje46fyw\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-install-es8ltb5c\aubio\
```

**Comment by piem** [comment]
hi @gabrielmonteiroflex 

Could it be that you don't have a compiler installed?

As mentionned in [aubio manual](https://aubio.org/manual/latest/python_module.html), a compiler is required to install aubio with `pip`. See also this page about [installing a compiler for Python on windows](https://wiki.python.org/moin/WindowsCompilers).

Alternatively, you could use [conda]() to install a [pre-compiled binary](https://aubio.org/manual/latest/python_module.html#installing-aubio-with-conda).

Let us know if that helps,

cheers, piem

**Comment by gabrielmonteiroflex** [comment]
Before this error, I had the error because of the missing C compiler. I installed the visual studio compiler and tried to install aubio again, then I got the error that is in this issue

**Comment by piem** [comment]
thanks for following up @gabrielmonteiroflex 

could you re-run the command with `pip install -Iv aubio` and paste the relevant error messages here?

cheers, piem

**Comment by gabrielmonteiroflex** [comment]
>  Info: libaubio was not installed or built locally with waf, adding src/
  workaround on win64 to avoid empty pre-processor output
  Running command: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
error
  ERROR: Failed building wheel for aubio

> Running command: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
  Running setup.py install for aubio ... error
Cleaning up...
  Removing source in C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-install-rc427od6\aubio
Removed build tracker 'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-req-tracker-7_t1ly98'
ERROR: Command "'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-install-rc427od6\\aubio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-record-2bjfyeal\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-install-rc427od6\aubio\
Exception information:
Traceback (most recent call last):
  File "c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_reqs
    **kwargs
  File "c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\req\req_install.py", line 953, in install
    spinner=spinner,
  File "c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-install-rc427od6\\aubio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-record-2bjfyeal\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-install-rc427od6\aubio\

**Comment by piem** [comment]
It seems you are using MSVC 14 to build for py 3.7 which should (or at least [could](https://ci.appveyor.com/project/piem/aubio)) work.

Could you try first upgrading `pip` with `pip install --upgrade pip`, then try installing aubio again with `pip install -Iv aubio`?

If that fails, could you run the following command manually from aubio's source code root directory and paste its output here?

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h`

thanks, piem

**Comment by piem** [comment]
hi @gabrielmonteiroflex 

any news on this?

thanks, piem

**Comment by gabrielmonteiroflex** [comment]
Hi piem,

I still couldn't install aubio in my PC the same error was happening. I tried installing it in my colleague's PC and it installed well. So I gave up installing it in my PC.

Thanks,

**Comment by gabrielmonteiroflex** [comment]
Hi piem,

I intend to use aubio to do speaker verification, do you have any aplications of something like this? Can you recommend it for me to help me in this process?

Thanks,

**Comment by piem** [comment]
Hi @gabrielmonteiroflex 

it would be nice to understand what exactly is the issue. I can't seem to find a useful error message in the logs you sent.

Could you try upgrading pip? You can use `pip install -Iv pip` for that, then try installing aubo again with `pip install -Iv aubio`.

please open a new issue for the speaker verification.

thanks, piem

**Comment by gabrielmonteiroflex** [comment]
I upgraded pip and tried installing aubio again. I will try posting the full log here because I couldn't find the problem

[log.txt](https://github.com/aubio/aubio/files/3149555/log.txt)

**Comment by piem** [comment]
hi again,

so @gabrielmonteiroflex had this error:

```
      File "python\lib\gen_external.py", line 129, in get_cpp_output
        % err_output.decode('utf8'))
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 44: invalid continuation byte
```

which looks very similar to issue #248 opened shortly after by @peter-volkov, who reported:

```
      File "python\lib\gen_external.py", line 129, in get_cpp_output
        % err_output.decode('utf8'))
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
```

i've just pushed a branch `fix/winencoding` to try sorting this out. you should be able to test it with:

    pip install git+https://github.com/aubio/aubio.git@fix/winencoding

let us know if that helps!

cheers, piem

**Comment by peter-volkov** [comment]
Thanks. It works for me

**Comment by gabrielmonteiroflex** [comment]
I am still getting an error:

````
Collecting git+https://github.com/aubio/aubio.git@fix/winencoding
  Cloning https://github.com/aubio/aubio.git (to revision fix/winencoding) to c:\users\gabrie~1.mon\appdata\local\temp\pip-req-build-40e28o_i
  Running command git clone -q https://github.com/aubio/aubio.git 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-req-build-40e28o_i'
  Running command git checkout -b fix/winencoding --track origin/fix/winencoding
  Branch 'fix/winencoding' set up to track remote branch 'fix/winencoding' from 'origin'.
  Switched to a new branch 'fix/winencoding'
Requirement already satisfied: numpy in c:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages (from aubio==0.5.0a0+66fff6c1) (1.16.3)
Building wheels for collected packages: aubio
  Building wheel for aubio (setup.py) ... error
  ERROR: Complete output from command 'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-req-build-40e28o_i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-wheel-ksf0px8h' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\cmd.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\cut.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\slicing.py -> build\lib.win-amd64-3.7\aubio
  copying python\lib\aubio\__init__.py -> build\lib.win-amd64-3.7\aubio
  running build_ext
  checking for aubio = 0.5.0~git+66fff6c1
  Running "pkg-config --libs --cflags aubio = 0.5.0~git+66fff6c1" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  Info: aubio 0.5.0~git+66fff6c1 was not found by pkg-config
  Info: looking for *optional* additional packages
  checking for libavcodec
  Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libavformat
  Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libavutil
  Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libswresample
  Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for libavresample
  Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for sndfile
  Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  checking for samplerate
  Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
  Info: libaubio was not installed or built locally with waf, adding src/
  workaround on win64 to avoid empty pre-processor output
  Running command: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
  Warning: preprocessor produced errors or warnings:
  Microsoft (R) C/C++ Optimizing Compiler VersÆo 19.00.24245 para x86
  Copyright (C) Microsoft Corporation. Todos os direitos reservados.

  aubio.h

  wrote python\gen\gen-dct.c
  wrote python\gen\gen-mfcc.c
  wrote python\gen\gen-specdesc.c
  wrote python\gen\gen-tss.c
  wrote python\gen\gen-pitch.c
  wrote python\gen\gen-onset.c
  wrote python\gen\gen-tempo.c
  wrote python\gen\gen-notes.c
  wrote python\gen\gen-sampler.c
  wrote python\gen\gen-wavetable.c
  wrote python\gen\aubio-generated.c
  wrote python\gen\aubio-generated.h
  building 'aubio._aubio' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\python
  creating build\temp.win-amd64-3.7\Release\python\ext
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\io
  creating build\temp.win-amd64-3.7\Release\src\notes
  creating build\temp.win-amd64-3.7\Release\src\onset
  creating build\temp.win-amd64-3.7\Release\src\pitch
  creating build\temp.win-amd64-3.7\Release\src\spectral
  creating build\temp.win-amd64-3.7\Release\src\synth
  creating build\temp.win-amd64-3.7\Release\src\tempo
  creating build\temp.win-amd64-3.7\Release\src\temporal
  creating build\temp.win-amd64-3.7\Release\src\utils
  creating build\temp.win-amd64-3.7\Release\python\gen
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DAUBIO_VERSION=0.5.0~git+66fff6c1 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_ERRNO_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_WIN_HACKS=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -Ic:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Isrc -Ipython\gen -Ic:\users\gabriel.monteiro\appdata\local\programs\python\python37\include -Ic:\users\gabriel.monteiro\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpython\ext\aubiomodule.c /Fobuild\temp.win-amd64-3.7\Release\python\ext\aubiomodule.obj
  aubiomodule.c
  c:\users\gabriel.monteiro\appdata\local\programs\python\python37\include\pyconfig.h(203): fatal error C1083: NÆo ‚ poss¡vel abrir arquivo incluir: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for aubio
  Running setup.py clean for aubio
Failed to build aubio
Installing collected packages: aubio
  Running setup.py install for aubio ... error
    ERROR: Complete output from command 'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-req-build-40e28o_i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-record-jzcs5ton\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    running build_ext
    checking for aubio = 0.5.0~git+66fff6c1
    Running "pkg-config --libs --cflags aubio = 0.5.0~git+66fff6c1" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    Info: aubio 0.5.0~git+66fff6c1 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libavformat
    Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libavutil
    Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libswresample
    Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for libavresample
    Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for sndfile
    Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    checking for samplerate
    Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'O sistema não pode encontrar o arquivo especificado', None, 2, None)
    Info: libaubio was not installed or built locally with waf, adding src/
    workaround on win64 to avoid empty pre-processor output
    Running command: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
    Warning: preprocessor produced errors or warnings:
    Microsoft (R) C/C++ Optimizing Compiler VersÆo 19.00.24245 para x86
    Copyright (C) Microsoft Corporation. Todos os direitos reservados.

    aubio.h

    wrote python\gen\gen-dct.c
    wrote python\gen\gen-mfcc.c
    wrote python\gen\gen-specdesc.c
    wrote python\gen\gen-tss.c
    wrote python\gen\gen-pitch.c
    wrote python\gen\gen-onset.c
    wrote python\gen\gen-tempo.c
    wrote python\gen\gen-notes.c
    wrote python\gen\gen-sampler.c
    wrote python\gen\gen-wavetable.c
    wrote python\gen\aubio-generated.c
    wrote python\gen\aubio-generated.h
    building 'aubio._aubio' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DAUBIO_VERSION=0.5.0~git+66fff6c1 -DUSE_LOCAL_AUBIO=1 -DHAVE_STDLIB_H=1 -DHAVE_STDIO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRING_H=1 -DHAVE_ERRNO_H=1 -DHAVE_C99_VARARGS_MACROS=1 -DHAVE_LIMITS_H=1 -DHAVE_STDARG_H=1 -DHAVE_MEMCPY_HACKS=1 -DHAVE_WIN_HACKS=1 -DHAVE_WAVWRITE=1 -DHAVE_WAVREAD=1 -Ipython/ext -Ic:\users\gabriel.monteiro\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Isrc -Ipython\gen -Ic:\users\gabriel.monteiro\appdata\local\programs\python\python37\include -Ic:\users\gabriel.monteiro\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpython\ext\aubiomodule.c /Fobuild\temp.win-amd64-3.7\Release\python\ext\aubiomodule.obj
    aubiomodule.c
    c:\users\gabriel.monteiro\appdata\local\programs\python\python37\include\pyconfig.h(203): fatal error C1083: NÆo ‚ poss¡vel abrir arquivo incluir: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\users\gabriel.monteiro\appdata\local\programs\python\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\GABRIE~1.MON\\AppData\\Local\\Temp\\pip-req-build-40e28o_i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-record-jzcs5ton\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GABRIE~1.MON\AppData\Local\Temp\pip-req-build-40e28o_i\
````

**Comment by piem** [comment]
hi @peter-volkov and @gabrielmonteiroflex 

Thank you both for your feedback. It seems the workaround prevents the decoding error, but mangles the non-ascii characters.

@gabrielmonteiroflex this looks like a different problem, one with your environment: the compiler complains it can not find some system header (`'basetsd.h': No such file or directory`). Please try the steps described [here](https://stackoverflow.com/a/42624713/2118678). If that doesn't help, please open a new report.

cheers, piem

**Comment by piem** [comment]
hi,

It looks to me that this workaround is worth merging. If I understand correctly, outside of python, UTF8 is not really supported on windows, so that there is no easy way to better convert the strings emitted by MSVC and other such tools into UTF8.

@gabrielmonteiroflex any progress on this on your side? 

cheers, piem

**Comment by gabrielmonteiroflex** [comment]
I could install after I did some steps:

I downloaded and installed an SDK from [here ](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/) to fix the header file basestd.h.

Then I got an additional error:
fatal error LNK1158: cannot run 'rc.exe'

To solve this:
I copied rc.exe and cdll.dll
from
    C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64
and pasted into visual studio installation folder
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

Thanks for the help piem!

**Comment by piem** [comment]
hi @gabrielmonteiroflex 

excellent, thank you for following up!

best, piem
