### ISSUE TITLE
Error while importing aubio-0.5.0a0+63fc1dfb with python

### ISSUE THREAD

**Issue by otori-bird** [aubio/aubio#266]
i used to have the  same problem like #264 and it was solved by 
$ pip install git+https://git.aubio.org/aubio/aubio/

After aubio-0.5.0a0 installed, i tried running demo_pitch.py and get errors below while importing aubio:

  File "G:\PYTHON\python3.5.4\lib\site-packages\aubio\__init__.py", line 26, in <module>
    from ._aubio import __version__ as version
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 945-946: invalid continuation byte

**Comment by piem** [comment]
hi @otori-bird 

thanks for your report, can you reproduce this with `python >= 3.6`?

cheers, piem

**Comment by Cjay-Chou** [comment]
I have same problem with
python 3.7
windows10
both version 4.9 and 5.0a0 same error.

`
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-c14661413ac3> in <module>
      3 
      4 import pandas as pd
----> 5 import aubio
      6 import pickle
      7 import os

c:\users\cjay\appdata\local\programs\python\python37\lib\site-packages\aubio\__init__.py in <module>
     24 
     25 import numpy
---> 26 from ._aubio import __version__ as version
     27 from ._aubio import float_type
     28 from ._aubio import *

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 945-946: invalid continuation byte
`

**Comment by JanvyHung** [comment]
> i used to have the same problem like #264 and it was solved by
> $ pip install git+https://git.aubio.org/aubio/aubio/
> 
> After aubio-0.5.0a0 installed, i tried running demo_pitch.py and get errors below while importing aubio:
> 
> File "G:\PYTHON\python3.5.4\lib\site-packages\aubio__init__.py", line 26, in
> from ._aubio import **version** as version
> UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 945-946: invalid continuation byte

I meet the same problem.Have you solved it?

**Comment by Cjay-Chou** [comment]
when i use macbook it solved but windows can't work

JanvyHung <notifications@github.com> 于 2020年3月30日周一 13:53写道：

**Comment by HorieYuan** [comment]
> > i used to have the same problem like #264 and it was solved by
> > $ pip install git+https://git.aubio.org/aubio/aubio/
> > After aubio-0.5.0a0 installed, i tried running demo_pitch.py and get errors below while importing aubio:
> > File "G:\PYTHON\python3.5.4\lib\site-packages\aubio__init__.py", line 26, in
> > from ._aubio import **version** as version
> > UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 945-946: invalid continuation byte
> 
> I meet the same problem.Have you solved it?

Hi, have you solved this problem?

**Comment by ShunyuanZ** [comment]
I encountered the same problem. Windows 10, Python 3.6. 
With Ptyhon 2.7, it worked fine.
