### ISSUE TITLE
ImportError on ibavcodec.so.58

### ISSUE THREAD

**Issue by Porshec** [aubio/aubio#288]
This error occured right after the install of ffmpeg using apt-get.

>>> import aubio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/aubio/__init__.py", line 26, in <module>
    from ._aubio import __version__ as version
ImportError: /usr/lib/arm-linux-gnueabihf/neon/vfp/libavcodec.so.58: undefined symbol: bcm_host_is_fkms_active

**Comment by piem** [comment]
hi @Porshec 

this seems to be an issue in the installation of libavcodec, unrelated to aubio.

could you try rebuilding aubio and see if that helps?

    pip uninstall -yv aubio
    pip install -v git+https://github.com/aubio/aubio

thx, piem
