### ISSUE TITLE
Can't install aubio on Windows 11 with Python 3 pip

### ISSUE THREAD

**Issue by studioadrienlucca** [aubio/aubio#373]
Hi,

I get an error when trying to install aubio via pip. This is the message that I get, I don't really understand what's wrong : 

C:\Users\proje>pip3 install aubio
Collecting aubio
  Using cached aubio-0.4.9.tar.gz (479 kB)
Requirement already satisfied: numpy in c:\python\python39\lib\site-packages (from aubio) (1.21.5)
Building wheels for collected packages: aubio
  Building wheel for aubio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\proje\\AppData\\Local\\Temp\\pip-install-6v9n_g2i\\aubio_799348abde2f45f78d483f4844baccb0\\setup.py'"'"'; __file__='"'"'C:\\Users\\proje\\AppData\\Local\\Temp\\pip-install-6v9n_g2i\\aubio_799348abde2f45f78d483f4844baccb0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\proje\AppData\Local\Temp\pip-wheel-cu61f5g0'
       cwd: C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\
  Complete output (68 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\aubio
  copying python\lib\aubio\cmd.py -> build\lib.win-amd64-3.9\aubio
  copying python\lib\aubio\cut.py -> build\lib.win-amd64-3.9\aubio
  copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-3.9\aubio
  copying python\lib\aubio\slicing.py -> build\lib.win-amd64-3.9\aubio
  copying python\lib\aubio\__init__.py -> build\lib.win-amd64-3.9\aubio
  running build_ext
  Package aubio was not found in the pkg-config search path.
  Perhaps you should add the directory containing `aubio.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'aubio' found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\setup.py", line 70, in <module>
      distrib = setup(name='aubio',
    File "C:\Python\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Python\Python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Python\Python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Python\Python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Python\Python39\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Python\Python39\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\moresetuptools.py", line 191, in build_extension
      extension.sources += generate_external(header, output_path, overwrite = False,
    File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\gen_external.py", line 271, in generate_external
      c_declarations = get_c_declarations(header, usedouble=usedouble)
    File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\gen_external.py", line 101, in get_c_declarations
      cpp_output = get_cpp_output(header=header, usedouble=usedouble)
    File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\gen_external.py", line 129, in get_cpp_output
      % err_output.decode('utf8'))
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 54: invalid start byte
  checking for aubio = 0.4.9
  Running "pkg-config --libs --cflags aubio = 0.4.9" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'aubio = 0.4.9'])
  Info: aubio 0.4.9 was not found by pkg-config
  Info: looking for *optional* additional packages
  checking for libavcodec
  checking for libavformat
  checking for libavutil
  checking for libswresample
  checking for libavresample
  checking for sndfile
  checking for samplerate
  Info: libaubio was not installed or built locally with waf, adding src/
  Running command: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
  ----------------------------------------
  ERROR: Failed building wheel for aubio
  Running setup.py clean for aubio
Failed to build aubio
Installing collected packages: aubio
    Running setup.py install for aubio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\proje\\AppData\\Local\\Temp\\pip-install-6v9n_g2i\\aubio_799348abde2f45f78d483f4844baccb0\\setup.py'"'"'; __file__='"'"'C:\\Users\\proje\\AppData\\Local\\Temp\\pip-install-6v9n_g2i\\aubio_799348abde2f45f78d483f4844baccb0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\proje\AppData\Local\Temp\pip-record-qs38o655\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python\Python39\Include\aubio'
         cwd: C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\
    Complete output (62 lines):
    running install
    running build
    running build_py
    running build_ext
    Package aubio was not found in the pkg-config search path.
    Perhaps you should add the directory containing `aubio.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'aubio' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\setup.py", line 70, in <module>
        distrib = setup(name='aubio',
      File "C:\Python\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python\Python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python\Python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python\Python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python\Python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Python\Python39\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Python\Python39\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\moresetuptools.py", line 191, in build_extension
        extension.sources += generate_external(header, output_path, overwrite = False,
      File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\gen_external.py", line 271, in generate_external
        c_declarations = get_c_declarations(header, usedouble=usedouble)
      File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\gen_external.py", line 101, in get_c_declarations
        cpp_output = get_cpp_output(header=header, usedouble=usedouble)
      File "C:\Users\proje\AppData\Local\Temp\pip-install-6v9n_g2i\aubio_799348abde2f45f78d483f4844baccb0\python\lib\gen_external.py", line 129, in get_cpp_output
        % err_output.decode('utf8'))
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 54: invalid start byte
    checking for aubio = 0.4.9
    Running "pkg-config --libs --cflags aubio = 0.4.9" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'aubio = 0.4.9'])
    Info: aubio 0.4.9 was not found by pkg-config
    Info: looking for *optional* additional packages
    checking for libavcodec
    checking for libavformat
    checking for libavutil
    checking for libswresample
    checking for libavresample
    checking for sndfile
    checking for samplerate
    Info: libaubio was not installed or built locally with waf, adding src/
    Running command: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\proje\\AppData\\Local\\Temp\\pip-install-6v9n_g2i\\aubio_799348abde2f45f78d483f4844baccb0\\setup.py'"'"'; __file__='"'"'C:\\Users\\proje\\AppData\\Local\\Temp\\pip-install-6v9n_g2i\\aubio_799348abde2f45f78d483f4844baccb0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\proje\AppData\Local\Temp\pip-record-qs38o655\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python\Python39\Include\aubio' Check the logs for full command output.

**Comment by sam-ln** [comment]
I'm experiencing the same problem using Windows 10 and Python 3.10.6

**Comment by sam-ln** [comment]
All versions up to aubio 0.4.7 can be installed on windows. 0.4.8 and 0.4.9 fail to install using pip.

**Comment by rakuri255** [comment]
No one can be installed anymore
