### ISSUE TITLE
Failed install with pip on Windows 10

### ISSUE THREAD

**Issue by phw** [aubio/aubio#385]
Trying to install aubio on Windows 10 with pypi fails:

```
> pip install aubio
Collecting aubio
  Using cached aubio-0.4.9.tar.gz (479 kB)
Requirement already satisfied: numpy in c:\users\developer\devel\picard\.venv\lib\site-packages (from aubio) (1.24.1)
Building wheels for collected packages: aubio
  Building wheel for aubio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\developer\devel\picard\.venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Developer\\AppData\\Local\\Temp\\pip-install-_kv_f244\\aubio_e0708ada9190468da13049c40126fdb1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Developer\\AppData\\Local\\Temp\\pip-install-_kv_f244\\aubio_e0708ada9190468da13049c40126fdb1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Developer\AppData\Local\Temp\pip-wheel-4xjiactl'
       cwd: C:\Users\Developer\AppData\Local\Temp\pip-install-_kv_f244\aubio_e0708ada9190468da13049c40126fdb1\
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  Generating grammar tables from C:\Program Files\Python38\lib\lib2to3\Grammar.txt
  Writing grammar tables to C:\Program Files\Python38\lib\lib2to3\Grammar3.8.10.final.0.pickle
  Writing failed: [Errno 13] Permission denied: 'C:\\Program Files\\Python38\\lib\\lib2to3\\Grammar3.8.10.final.0.pickle'
  Generating grammar tables from C:\Program Files\Python38\lib\lib2to3\PatternGrammar.txt
  Writing grammar tables to C:\Program Files\Python38\lib\lib2to3\PatternGrammar3.8.10.final.0.pickle
  Writing failed: [Errno 13] Permission denied: 'C:\\Program Files\\Python38\\lib\\lib2to3\\PatternGrammar3.8.10.final.0.pickle'
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\aubio
  copying python\lib\aubio\cmd.py -> build\lib.win-amd64-3.8\aubio
  copying python\lib\aubio\cut.py -> build\lib.win-amd64-3.8\aubio
  copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-3.8\aubio
  copying python\lib\aubio\slicing.py -> build\lib.win-amd64-3.8\aubio
  copying python\lib\aubio\__init__.py -> build\lib.win-amd64-3.8\aubio
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Developer\AppData\Local\Temp\pip-install-_kv_f244\aubio_e0708ada9190468da13049c40126fdb1\setup.py", line 70, in <module>
      distrib = setup(name='aubio',
    File "c:\users\developer\devel\picard\.venv\lib\site-packages\setuptools\__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\Python38\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files\Python38\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\developer\devel\picard\.venv\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "C:\Program Files\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\Python38\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Program Files\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\Python38\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Program Files\Python38\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Program Files\Python38\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Developer\AppData\Local\Temp\pip-install-_kv_f244\aubio_e0708ada9190468da13049c40126fdb1\python\lib\moresetuptools.py", line 191, in build_extension
      extension.sources += generate_external(header, output_path, overwrite = False,
    File "C:\Users\Developer\AppData\Local\Temp\pip-install-_kv_f244\aubio_e0708ada9190468da13049c40126fdb1\python\lib\gen_external.py", line 271, in generate_external
      c_declarations = get_c_declarations(header, usedouble=usedouble)
    File "C:\Users\Developer\AppData\Local\Temp\pip-install-_kv_f244\aubio_e0708ada9190468da13049c40126fdb1\python\lib\gen_external.py", line 101, in get_c_declarations
      cpp_output = get_cpp_output(header=header, usedouble=usedouble)
    File "C:\Users\Developer\AppData\Local\Temp\pip-install-_kv_f244\aubio_e0708ada9190468da13049c40126fdb1\python\lib\gen_external.py", line 129, in get_cpp_output
      % err_output.decode('utf8'))
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 62: invalid start byte
  checking for aubio = 0.4.9
  Running "pkg-config --libs --cflags aubio = 0.4.9" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  Info: aubio 0.4.9 was not found by pkg-config
  Info: looking for *optional* additional packages
  checking for libavcodec
  Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  checking for libavformat
  Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  checking for libavutil
  Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  checking for libswresample
  Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  checking for libavresample
  Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  checking for sndfile
  Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  checking for samplerate
  Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
  Info: libaubio was not installed or built locally with waf, adding src/
  Running command: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
  ----------------------------------------
  ERROR: Failed building wheel for aubio
  Running setup.py clean for aubio
Failed to build aubio
```

The trouble seems to be at `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 62: invalid start byte`.

**Comment by Jackowski3k** [comment]
Same problem. No idea where that char comes from. Also win10 here.

**Comment by piem** [comment]
howdy,

can you try with the latest git version? this seems to be a duplicate of #247 and #248 

cheers, piem

**Comment by piem** [comment]
hi @phw 

thanks for your report.

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 62: invalid start byte
```

i believe this was fixed with 46f78469bbc589e7f981d3fad2dc917e9d6222ae, please reopen if needed,

cheers, piem
