### ISSUE TITLE
source_avcodec: error when sending packet

### ISSUE THREAD

**Issue by friki67** [aubio/aubio#388]
Hello

Archlinux here. Aubio 0.4.9, installed using package python-aubio.

I did` aubio tempo "/mnt/storage/data/media/music/Compilations/Blondie-The Best Of Blondie [1981]/03 - Blondie - The Tide Is High.mp3"`

and got 

```
[mp3 @ 0x5655280635c0] Estimating duration from bitrate, this may be inaccurate
[mp3float @ 0x565528069580] Header missing                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                            
  File "/home/archlinux/.local/bin/aubio", line 8, in <module>
    sys.exit(main())
  File "/home/archlinux/.local/lib/python3.10/site-packages/aubio/cmd.py", line 598, in main
    block, read = a_source()
RuntimeError: AUBIO ERROR: source_avcodec: error when sending packet for /mnt/storage/data/media/music/Compilations/Blondie-The Best Of Blondie [1981]/03 - Blondie - The Tide Is High.mp3
```
Why? Can I fix it?

**Comment by piem** [comment]
hi @friki67 

can you read the files with another tool such as `ffprobe`? what changed before it stopped working?

cheers, piem

**Comment by friki67** [comment]
Hello! ffprobe gives me a curious reference to the initial message from aubio:

```
ffprobe "/mnt/storage/data/media/music/Compilations/Blondie-The Best Of Blondie [1981]/03 - Blondie - The Tide Is High.mp3"
ffprobe version n5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mp3 @ 0x555964622140] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/mnt/storage/data/media/music/Compilations/Blondie-The Best Of Blondie [1981]/03 - Blondie - The Tide Is High.mp3':
  Metadata:
    title           : The Tide Is High
    artist          : Blondie
    track           : 3/12
    album           : The Best Of Blondie
    disc            : 1/1
    date            : 1981
    genre           : New Wave
    TBPM            : 0
    compilation     : 1
    TDOR            : 1981
    TMED            : Vinyl
    album_artist    : Blondie
    TIPL            : arranger
    publisher       : Chrysalis
    CATALOGNUMBER   : CHR 1337
    MusicBrainz Album Id: 162581
    MusicBrainz Artist Id: 16655
    MusicBrainz Album Artist Id: 16655
    MusicBrainz Release Group Id: 64517
    ID3v1 Comment   : www.mp3jamboree.com
    MusicBrainz Album Release Country: US
    lyrics-XXX      : Tekst piosenki:
                    : The tide is high but I'm holding on
                    : I'm gonna be your number one
                    : I'm not the kind of girl
                    : Who gives up just like that
                    : Oh, no
                    : 
                    : It's not the things you do
                    : That tease and wound me bad
                    : But it's the way you do
                    : The things you do to me
                    : I'm not the kind of girl
                    : Who gives up just like that
                    : Oh, no
                    : 
                    : The tide is high but I'm holding on
                    : I'm gonna be your number one
                    : Number one, number one
                    : 
                    : Every girl wants you to be her man
                    : But I'll wait my dear 'til it's my turn
                    : I'm not the kind of girl
                    : Who gives up just like that
                    : Oh, no
                    : 
                    : The tide is high but I'm holding on
                    : I'm gonna be your number one
                    : Number one, number one
                    : 
                    : Every girl wants you to be her man
                    : But I'll wait my dear 'til it's my turn
                    : I'm not the kind of girl
                    : Who gives up just like that
                    : Oh, no
                    : The tide is high but I'm holding on
                    : I'm gonna be your number one
                    : {Repeat}
                    : Dodaj interpretację do tego tekstu »
                    : 
                    : Historia edycji tekstu
  Duration: 00:04:42.13, start: 0.000000, bitrate: 128 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
```
Most of the files are working, but some albums are failing. They play ok, but I cannot use aubio to get the tempo or beats.
