### ISSUE TITLE
Python: ImportError: libaubio.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danstowell** [aubio/aubio#5]
Building the python aubio from git (7fc5ba2) doesn't seem to work for me, on Ubuntu 13.04:

```
(~/dev/aubio/python) % python setup.py build
running build
running build_py
running build_ext
running build_scripts

(~/dev/aubio/python) % sudo python setup.py install
running install
running build
running build_py
running build_ext
running build_scripts
running install_lib
creating /usr/local/lib/python2.7/dist-packages/aubio
copying build/lib.linux-x86_64-2.7/aubio/_aubio.so -> /usr/local/lib/python2.7/dist-packages/aubio
copying build/lib.linux-x86_64-2.7/aubio/midiconv.py -> /usr/local/lib/python2.7/dist-packages/aubio
copying build/lib.linux-x86_64-2.7/aubio/__init__.py -> /usr/local/lib/python2.7/dist-packages/aubio
byte-compiling /usr/local/lib/python2.7/dist-packages/aubio/midiconv.py to midiconv.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/aubio/__init__.py to __init__.pyc
running install_scripts
changing mode of /usr/local/bin/aubiocut to 775
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/aubio-0.4.0alpha.egg-info

(~/dev/aubio/python) % ls /usr/local/lib/python2.7/dist-packages/aubio
_aubio.so*  __init__.py  __init__.pyc  midiconv.py  midiconv.pyc
```

Then opening a new terminal window:

```
(~) % python
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aubio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/aubio/__init__.py", line 4, in <module>
    from _aubio import *
ImportError: libaubio.so.4: cannot open shared object file: No such file or directory
>>> 

```

**Comment by toolowner** [comment]
@danstowell You saved my day :1st_place_medal:

**Comment by piem** [comment]
hi @danstowell, @toolowner, and everyone,

First things first: I would recommend **not** using sudo when building a project. This will prevent polluting `/usr` with files you may not need, and will likely forget to uninstall.

Also, sometimes, one has no root or sudo permissions, so if everything can be done in the user world, it will be easier to deploy for everyone.

There is a script just for that in the aubio source tree, which can be *sourced* as follows:

```console
$ source scripts/setenv_local.sh 
export LD_LIBRARY_PATH=/home/piem/projects/aubio/build/src
 ```

As shown in the above example, the script simply exports one environment variable, and prints out its value. This script should work on osx as well, where the variable name has been changed.

Using this script along with a python `virtualenv` is not an issue, since `virtualenv` does not export this variable. It can be used before or after activating a virtualenv with `source /path/to/myvenv/bin/activate`.

___

Now, even when using sudo, I'm not sure how users end up in this situation. I have **never** needed to use `ldconfig` manually myself.

There are 2 ways of building the python module:
- linking against libaubio
- including the library binary code inside the python module 

To determine weather libaubio is found and may be used, `setup.py` follows theses steps:
- if a version of aubio is already installed on the system, its version is checked for with `pkg-config --libs --cflags aubio = <source_tree_version>`. If the version matches exactly, it will be used.
- if libaubio.so is found in `./build/src`, the python extension will use it to link against it
- otherwise, the library source code in `src/` will be built inside the python extension

If libaubio was installed in a non-standard location, exporting `PKG_CONFIG_PATH` will allow `pkg-config` find the correct path in the first step.

These steps are defined in `python/lib/moresetuptools.py`.

Here is an example of output when running `./setup.py build` after `./waf configure build`:
```
[...]
checking for aubio = 0.5.0~git+1753a0bd+mods
Package aubio was not found in the pkg-config search path.
Perhaps you should add the directory containing `aubio.pc'
to the PKG_CONFIG_PATH environment variable
No package 'aubio' found
Running "pkg-config --libs --cflags aubio = 0.5.0~git+1753a0bd+mods" failed: CalledProcessError()
Info: aubio 0.5.0~git+1753a0bd+mods was not found by pkg-config
Info: using locally built libaubio
[...]
```

I guess the documentation could be clarified with some of these informations. I'm re-opening this bug as a reminder. Please let us know here if I missed something.

cheers, piem

**Comment by toolowner** [comment]
Thanks @piem for noticing that <3
