### ISSUE TITLE
aubioonset mp3 with ffmpeg on Ubuntu

### ISSUE THREAD

**Issue by fbukevin** [aubio/aubio#81]
Hi, guys.

I installed aubio python module and download the python demo [demo_onset.py](https://github.com/aubio/aubio/blob/master/python/demos/demo_onset.py). on both Windows 7 and Linux Mint 18.1 (macOS is fine). With Python version 3.6, when I used `python3 demo_onset.py test.mp3`, the error output was as following:

```
AUBIO ERROR: source_wavread: could not find RIFF header in test.mp3
AUBIO ERROR: source: failed creating aubio source with test.mp3 at samplerate 0 with hop_size 256
Traceback (most recent call last):
File "demo_onset.py", line 18, in <module>
s = source(filename, samplerate, hop_s)
RuntimeError: error creating source with "test.mp3"
```

I then installed ` libavcodec-dev libavformat-dev libavresample-dev libavutil-dev` and rebuilt aubio with `./waf configure build` and `sudo ./waf install`, also exported `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/src`. But I got the same error still.

I got the same problem in python 2.7. Did I lose any step or prerequisite?

**Comment by fbukevin** [comment]
The following is what my `pip3 install aubio` output:

```
veck@veck-VirtualBox ~ $ pip3 install aubio
Collecting aubio
  Using cached aubio-0.4.3.post1.tar.gz
Collecting numpy (from aubio)
  Using cached numpy-1.11.3-cp35-cp35m-manylinux1_x86_64.whl
Building wheels for collected packages: aubio
  Running setup.py bdist_wheel for aubio ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x1wcq6lm/aubio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpcyjz5mjdpip-wheel- --python-tag cp35:
  Warning: libaubio was not built with waf, adding src/
  Info: looking for *optional* additional packages
  Package jack was not found in the pkg-config search path.
  Perhaps you should add the directory containing `jack.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'jack' found
  Running "pkg-config --libs --cflags jack" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'jack'])
  Package sndfile was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sndfile.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sndfile' found
  Running "pkg-config --libs --cflags sndfile" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'sndfile'])
  Package samplerate was not found in the pkg-config search path.
  Perhaps you should add the directory containing `samplerate.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'samplerate' found
  Running "pkg-config --libs --cflags samplerate" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'samplerate'])
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for aubio
  Running setup.py clean for aubio
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x1wcq6lm/aubio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Warning: libaubio was not built with waf, adding src/
  Info: looking for *optional* additional packages
  Package jack was not found in the pkg-config search path.
  Perhaps you should add the directory containing `jack.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'jack' found
  Running "pkg-config --libs --cflags jack" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'jack'])
  Package sndfile was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sndfile.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sndfile' found
  Running "pkg-config --libs --cflags sndfile" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'sndfile'])
  Package samplerate was not found in the pkg-config search path.
  Perhaps you should add the directory containing `samplerate.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'samplerate' found
  Running "pkg-config --libs --cflags samplerate" failed: CalledProcessError(1, ['pkg-config', '--libs', '--cflags', 'samplerate'])
  running clean
  removing 'python/gen' (and everything under it)
  error: [Errno 2] No such file or directory: 'python/gen'
  
  ----------------------------------------
  Failed cleaning build dir for aubio
Failed to build aubio
Installing collected packages: numpy, aubio
  Running setup.py install for aubio ... done
Successfully installed aubio-0.4.3.post1 numpy-1.11.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
veck@veck-VirtualBox ~ $ ^C
veck@veck-VirtualBox ~ $ 

```

**Comment by piem** [comment]
Hi @fbukevin 

What happens if you try installing from git?

```
$ pip3 install git+https://github.com/aubio/aubio.git/
```

If that doesn't work, does installing python-wheel help? and upgrading pip?

```
$ pip3 install --upgrade wheels
$ pip3 install --upgrade pip
```
Best, piem

**Comment by fbukevin** [comment]
I've installed from git and the output is:

```
Traceback (most recent call last):
  File "demo_onset.py", line 4, in <module>
    from aubio import source, onset
  File "/usr/local/lib/python2.7/dist-packages/aubio/__init__.py", line 4, in <module>
    from ._aubio import __version__ as version
ImportError: libaubio.so.5: cannot open shared object file: No such file or directory
```

Interestingly, I can successfully import it in REPL interface.

Installing wheels and upgrade pip does not help.

**Comment by piem** [comment]
Hi @fbukevin ,

Could you send the output of the pip3 install command?

In the example above, `demo_onset.py` tries to load aubio compiled for python2.7 and against libaubio.so.5, but libaubio.so.5 has not been installed. You could do try one of the following:

 - install libaubio in a standard location (e.g. `/usr/local/lib` for instance)
 - tell python where to find your custom libaubio (e.g. `export LD_LIBRARY_PATH=$HOME/aubio/build/src`)
 - rebuild python2.7 aubio to not use libaubio (`pip uninstall -y -v aubio && pip install ...`)

best, Paul

**Comment by fbukevin** [comment]
Hi @piem,

Thanks! I export the LD_LIBRARY_PATH, and it worked!!!

**Comment by piem** [comment]
Hi @fbukevin 

Great! can you also get python aubio to work with ffmpeg on windows?

The package is currently tested on appveyor, but without ffmpeg.
See https://ci.appveyor.com/project/piem/aubio

best, piem

**Comment by piem** [comment]
Hi @fbukevin ,

Closing this issue (for ubuntu). Please open a new issue if you have troubles compiling on windows.

cheers, Paul

**Comment by fbukevin** [comment]
Hi @piem,

Yes, all works fine. Thanks for your help!
