### ISSUE TITLE
importing mp3 file

### ISSUE THREAD

**Issue by PostsDesert** [aubio/aubio#85]
Hello, I'm trying to import a mp3 into aubio but I can't get it to use source_libav instead of source_wavread. The test file i've been using is `demo_bpm_extract.py` on python 3. I have tried installing these `libavcodec-dev libavformat-dev libavresample-dev libavutil-dev` packages but it had no noticeable affect. Any help would be greatly appreciated. Thanks, Griffith 
```Traceback (most recent call last):
  File "demo_bpm_extract.py", line 62, in <module>
    bpm = get_file_bpm(f)
  File "demo_bpm_extract.py", line 27, in get_file_bpm
    s = source(path, samplerate, hop_s)
RuntimeError: AUBIO ERROR: source_wavread: Failed opening videoplayback.mp3 (could not find RIFF header)```

**Comment by piem** [comment]
Hello @PostsDesert,

Did you recompile python-aubio after installing libav*-dev?

Could you paste here the output of the following commands:

    $ pip uninstall -y -v aubio && pip install --user -v aubio

Best, Paul

**Comment by PostsDesert** [comment]
No luck unfortunately. It still returns the same error. Here is the pip output.
```Uninstalling aubio-0.4.4:
  Removing file or directory /home/griffith/.local/bin/aubiocut
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/DESCRIPTION.rst
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/INSTALLER
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/METADATA
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/RECORD
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/WHEEL
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/metadata.json
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/top_level.txt
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__init__.py
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__pycache__/__init__.cpython-35.pyc
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__pycache__/midiconv.cpython-35.pyc
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__pycache__/slicing.cpython-35.pyc
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/_aubio.cpython-35m-x86_64-linux-gnu.so
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/midiconv.py
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/slicing.py
  Successfully uninstalled aubio-0.4.4
Collecting aubio
  1 location(s) to search for versions of aubio:
  * https://pypi.python.org/simple/aubio/
  Getting page https://pypi.python.org/simple/aubio/
  Looking up "https://pypi.python.org/simple/aubio/" in the cache
  Current age based on date: 113
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 113
  Analyzing links from page https://pypi.python.org/simple/aubio/
    Skipping link https://pypi.python.org/packages/2d/41/aa46abdf8a584217a28b8a907c61541b747885ea3aafa0644d3425afe99c/aubio-0.4.3a2-cp27-cp27m-win32.whl#md5=c3519639ac9774d134b28056995563d0 (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/72/83/5a300960dd8c62227fc2d847089a3b5b47fb1c5dee12864d1d4d2f2b0645/aubio-0.4.3.post1.tar.gz#md5=8ddaa8cc671dce32e24b00b351798f79 (from https://pypi.python.org/simple/aubio/), version: 0.4.3.post1
    Skipping link https://pypi.python.org/packages/78/83/0fd8e94f048047d004f2c76d4745e498d90c5d740f7aec6b3a69b67ec490/aubio-0.4.3a2-cp35-cp35m-win_amd64.whl#md5=995a24ebe2317914129c27d49a380617 (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/82/84/eaa6344c65304f4964ce40426b437eae8bed3c41017332ea06fac5408e61/aubio-0.4.3a2-py3.4-linux-x86_64.egg#md5=596710330fea4a00026d787312630efb (from https://pypi.python.org/simple/aubio/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/87/6f/932ec3e1857a72d915e500b8bc84546364004ce0908a692cffb236fa5be7/aubio-0.4.3a1-cp27-cp27m-macosx_10_11_intel.whl#md5=af7f8267c67b7e565112e29063b04068 (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a6/f4/5e72e261bf205b232bc9c90ff59f6c4b787290a3001fe8de66effbf674ce/aubio-0.4.3a2-cp27-cp27m-macosx_10_11_intel.whl#md5=950e449a0af891318881c48b1c9302af (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/a9/1a/83c93ad2c0a022b6b7846ebfff7873c1fd91abd34252a0db98e3c4a6e932/aubio-0.4.3a1.tar.gz#md5=f7166e62922d66b83e802cdad9f91969 (from https://pypi.python.org/simple/aubio/), version: 0.4.3a1
    Found link https://pypi.python.org/packages/c3/39/37ddc69b353277ea3df46a18f42acec572dcd5b4636c79cb0694374b209b/aubio-0.4.3a2.tar.gz#md5=e79694114aafb5e1cdf552fb0a7adab4 (from https://pypi.python.org/simple/aubio/), version: 0.4.3a2
    Skipping link https://pypi.python.org/packages/fd/8d/08f8f54aa1fe5ed05157f2052ad13d0f6432fce9b7c1f357aae65fd64909/aubio-0.4.3a2-py2.7-linux-x86_64.egg#md5=48334f8242d6f3c5ca9887c454bf728f (from https://pypi.python.org/simple/aubio/); unsupported archive format: .egg
    Found link https://pypi.python.org/packages/ff/f1/63fd92be1c59d4b1e75fe5be66e4dc37389b97ab71a5b47401036908ee68/aubio-0.4.4.tar.gz#md5=b8b24730067c8926c264eb232acaee1d (from https://pypi.python.org/simple/aubio/), version: 0.4.4
  Using version 0.4.4 (newest of versions: 0.4.3.post1, 0.4.4)
  Using cached wheel link: file:///home/griffith/.cache/pip/wheels/c1/92/36/411b69ea9c98ecc0bf9fa91eb8f030e0f07cec963248ffae8d/aubio-0.4.4-cp35-cp35m-linux_x86_64.whl
Requirement already satisfied: numpy in ./.local/lib/python3.5/site-packages (from aubio)
Installing collected packages: aubio

Successfully installed aubio-0.4.4
Cleaning up...```

Could using python3.5 instead of 3.6 have any affect on this issue?

**Comment by piem** [comment]
Hi @PostsDesert 

pip gets to used the cached version of a locally built .whl package:

```
  Using cached wheel link: file:///home/griffith/.cache/pip/wheels/c1/92/36/411b69ea9c98ecc0bf9fa91eb8f030e0f07cec963248ffae8d/aubio-0.4.4-cp35-cp35m-linux_x86_64.whl
```

Could you try removing or moving away this file to make sure the package gets really rebuilt?

thanks, piem

**Comment by PostsDesert** [comment]
Okay so the package appears to be rebuilding but it returns a different error.
```
Uninstalling aubio-0.4.4:
  Removing file or directory /home/griffith/.local/bin/aubiocut
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/DESCRIPTION.rst
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/INSTALLER
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/METADATA
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/RECORD
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/WHEEL
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/metadata.json
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio-0.4.4.dist-info/top_level.txt
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__init__.py
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__pycache__/__init__.cpython-35.pyc
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__pycache__/midiconv.cpython-35.pyc
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/__pycache__/slicing.cpython-35.pyc
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/_aubio.cpython-35m-x86_64-linux-gnu.so
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/midiconv.py
  Removing file or directory /home/griffith/.local/lib/python3.5/site-packages/aubio/slicing.py
  Successfully uninstalled aubio-0.4.4
Collecting aubio
  1 location(s) to search for versions of aubio:
  * https://pypi.python.org/simple/aubio/
  Getting page https://pypi.python.org/simple/aubio/
  Looking up "https://pypi.python.org/simple/aubio/" in the cache
  Current age based on date: 11369
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/aubio/ HTTP/1.1" 200 936
  Updating cache with response from "https://pypi.python.org/simple/aubio/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/aubio/
    Skipping link https://pypi.python.org/packages/2d/41/aa46abdf8a584217a28b8a907c61541b747885ea3aafa0644d3425afe99c/aubio-0.4.3a2-cp27-cp27m-win32.whl#md5=c3519639ac9774d134b28056995563d0 (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/72/83/5a300960dd8c62227fc2d847089a3b5b47fb1c5dee12864d1d4d2f2b0645/aubio-0.4.3.post1.tar.gz#md5=8ddaa8cc671dce32e24b00b351798f79 (from https://pypi.python.org/simple/aubio/), version: 0.4.3.post1
    Skipping link https://pypi.python.org/packages/78/83/0fd8e94f048047d004f2c76d4745e498d90c5d740f7aec6b3a69b67ec490/aubio-0.4.3a2-cp35-cp35m-win_amd64.whl#md5=995a24ebe2317914129c27d49a380617 (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/82/84/eaa6344c65304f4964ce40426b437eae8bed3c41017332ea06fac5408e61/aubio-0.4.3a2-py3.4-linux-x86_64.egg#md5=596710330fea4a00026d787312630efb (from https://pypi.python.org/simple/aubio/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/87/6f/932ec3e1857a72d915e500b8bc84546364004ce0908a692cffb236fa5be7/aubio-0.4.3a1-cp27-cp27m-macosx_10_11_intel.whl#md5=af7f8267c67b7e565112e29063b04068 (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a6/f4/5e72e261bf205b232bc9c90ff59f6c4b787290a3001fe8de66effbf674ce/aubio-0.4.3a2-cp27-cp27m-macosx_10_11_intel.whl#md5=950e449a0af891318881c48b1c9302af (from https://pypi.python.org/simple/aubio/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/a9/1a/83c93ad2c0a022b6b7846ebfff7873c1fd91abd34252a0db98e3c4a6e932/aubio-0.4.3a1.tar.gz#md5=f7166e62922d66b83e802cdad9f91969 (from https://pypi.python.org/simple/aubio/), version: 0.4.3a1
    Found link https://pypi.python.org/packages/c3/39/37ddc69b353277ea3df46a18f42acec572dcd5b4636c79cb0694374b209b/aubio-0.4.3a2.tar.gz#md5=e79694114aafb5e1cdf552fb0a7adab4 (from https://pypi.python.org/simple/aubio/), version: 0.4.3a2
    Skipping link https://pypi.python.org/packages/fd/8d/08f8f54aa1fe5ed05157f2052ad13d0f6432fce9b7c1f357aae65fd64909/aubio-0.4.3a2-py2.7-linux-x86_64.egg#md5=48334f8242d6f3c5ca9887c454bf728f (from https://pypi.python.org/simple/aubio/); unsupported archive format: .egg
    Found link https://pypi.python.org/packages/ff/f1/63fd92be1c59d4b1e75fe5be66e4dc37389b97ab71a5b47401036908ee68/aubio-0.4.4.tar.gz#md5=b8b24730067c8926c264eb232acaee1d (from https://pypi.python.org/simple/aubio/), version: 0.4.4
  Using version 0.4.4 (newest of versions: 0.4.3.post1, 0.4.4)
  Looking up "https://pypi.python.org/packages/ff/f1/63fd92be1c59d4b1e75fe5be66e4dc37389b97ab71a5b47401036908ee68/aubio-0.4.4.tar.gz" in the cache
  Current age based on date: 70146
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 70146
  Using cached aubio-0.4.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/ff/f1/63fd92be1c59d4b1e75fe5be66e4dc37389b97ab71a5b47401036908ee68/aubio-0.4.4.tar.gz#md5=b8b24730067c8926c264eb232acaee1d (from https://pypi.python.org/simple/aubio/)
  Running setup.py (path:/tmp/pip-build-jtybangf/aubio/setup.py) egg_info for package aubio
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/aubio.egg-info
    writing requirements to pip-egg-info/aubio.egg-info/requires.txt
    writing pip-egg-info/aubio.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/aubio.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/aubio.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/aubio.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/aubio.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'waflib/__pycache__/*'
    warning: no previously-included files found matching 'doc/full.cfg'
    warning: no previously-included files found matching 'python/gen/*'
    writing manifest file 'pip-egg-info/aubio.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-jtybangf/aubio has version 0.4.4, which satisfies requirement aubio from https://pypi.python.org/packages/ff/f1/63fd92be1c59d4b1e75fe5be66e4dc37389b97ab71a5b47401036908ee68/aubio-0.4.4.tar.gz#md5=b8b24730067c8926c264eb232acaee1d
Requirement already satisfied: numpy in ./.local/lib/python3.5/site-packages (from aubio)
Building wheels for collected packages: aubio
  Running setup.py bdist_wheel for aubio ...   Destination directory: /tmp/tmplcv27j37pip-wheel-
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtybangf/aubio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmplcv27j37pip-wheel- --python-tag cp35
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/aubio
  copying python/lib/aubio/midiconv.py -> build/lib.linux-x86_64-3.5/aubio
  copying python/lib/aubio/slicing.py -> build/lib.linux-x86_64-3.5/aubio
  copying python/lib/aubio/__init__.py -> build/lib.linux-x86_64-3.5/aubio
  running build_ext
  checking for aubio
  Running command: x86_64-linux-gnu-gcc -pthread -E -Wdate-time -D_FORTIFY_SOURCE=2 -DAUBIO_UNSTABLE=1 -Isrc src/aubio.h
  wrote python/gen/gen-wavetable.c
  wrote python/gen/gen-notes.c
  wrote python/gen/gen-tss.c
  wrote python/gen/gen-tempo.c
  wrote python/gen/gen-pitch.c
  wrote python/gen/gen-sampler.c
  wrote python/gen/gen-onset.c
  wrote python/gen/gen-specdesc.c
  wrote python/gen/gen-mfcc.c
  wrote python/gen/aubio-generated.c
  wrote python/gen/aubio-generated.h
  building 'aubio._aubio' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/python
  creating build/temp.linux-x86_64-3.5/python/ext
  creating build/temp.linux-x86_64-3.5/python/gen
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6tVwKN/python3.5-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DAUBIO_VERSION=0.4.4 -Ipython/ext -Ipython/gen -I/home/griffith/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c python/ext/aubiomodule.c -o build/temp.linux-x86_64-3.5/python/ext/aubiomodule.o
  python/ext/aubiomodule.c: In function ‘aubio_log_function’:
  python/ext/aubiomodule.c:272:16: error: ‘AUBIO_LOG_ERR’ undeclared (first use in this function)
     if (level == AUBIO_LOG_ERR) {
                  ^~~~~~~~~~~~~
  python/ext/aubiomodule.c:272:16: note: each undeclared identifier is reported only once for each function it appears in
  python/ext/aubiomodule.c: In function ‘initaubio’:
  python/ext/aubiomodule.c:339:3: warning: implicit declaration of function ‘aubio_log_set_level_function’ [-Wimplicit-function-declaration]
     aubio_log_set_level_function(AUBIO_LOG_ERR, aubio_log_function, NULL);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  python/ext/aubiomodule.c:339:32: error: ‘AUBIO_LOG_ERR’ undeclared (first use in this function)
     aubio_log_set_level_function(AUBIO_LOG_ERR, aubio_log_function, NULL);
                                  ^~~~~~~~~~~~~
  python/ext/aubiomodule.c:340:32: error: ‘AUBIO_LOG_WRN’ undeclared (first use in this function)
     aubio_log_set_level_function(AUBIO_LOG_WRN, aubio_log_function, NULL);
                                  ^~~~~~~~~~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
error
  Failed building wheel for aubio
  Running setup.py clean for aubio
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtybangf/aubio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'python/gen' (and everything under it)
Failed to build aubio
Installing collected packages: aubio
  Running setup.py install for aubio ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtybangf/aubio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7a2rv5h9-record/install-record.txt --single-version-externally-managed --compile --user --prefix=
    running install
    running build
    running build_py
    running build_ext
    checking for aubio
    Running command: x86_64-linux-gnu-gcc -pthread -E -Wdate-time -D_FORTIFY_SOURCE=2 -DAUBIO_UNSTABLE=1 -Isrc src/aubio.h
    wrote python/gen/gen-onset.c
    wrote python/gen/gen-tempo.c
    wrote python/gen/gen-mfcc.c
    wrote python/gen/gen-pitch.c
    wrote python/gen/gen-sampler.c
    wrote python/gen/gen-wavetable.c
    wrote python/gen/gen-tss.c
    wrote python/gen/gen-specdesc.c
    wrote python/gen/gen-notes.c
    wrote python/gen/aubio-generated.c
    wrote python/gen/aubio-generated.h
    building 'aubio._aubio' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6tVwKN/python3.5-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DAUBIO_VERSION=0.4.4 -Ipython/ext -Ipython/gen -I/home/griffith/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c python/ext/aubiomodule.c -o build/temp.linux-x86_64-3.5/python/ext/aubiomodule.o
    python/ext/aubiomodule.c: In function ‘aubio_log_function’:
    python/ext/aubiomodule.c:272:16: error: ‘AUBIO_LOG_ERR’ undeclared (first use in this function)
       if (level == AUBIO_LOG_ERR) {
                    ^~~~~~~~~~~~~
    python/ext/aubiomodule.c:272:16: note: each undeclared identifier is reported only once for each function it appears in
    python/ext/aubiomodule.c: In function ‘initaubio’:
    python/ext/aubiomodule.c:339:3: warning: implicit declaration of function ‘aubio_log_set_level_function’ [-Wimplicit-function-declaration]
       aubio_log_set_level_function(AUBIO_LOG_ERR, aubio_log_function, NULL);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    python/ext/aubiomodule.c:339:32: error: ‘AUBIO_LOG_ERR’ undeclared (first use in this function)
       aubio_log_set_level_function(AUBIO_LOG_ERR, aubio_log_function, NULL);
                                    ^~~~~~~~~~~~~
    python/ext/aubiomodule.c:340:32: error: ‘AUBIO_LOG_WRN’ undeclared (first use in this function)
       aubio_log_set_level_function(AUBIO_LOG_WRN, aubio_log_function, NULL);
                                    ^~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-jtybangf/aubio
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtybangf/aubio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7a2rv5h9-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-jtybangf/aubio/
Exception information:
Traceback (most recent call last):
  File "/home/griffith/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/griffith/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/griffith/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/griffith/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/griffith/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtybangf/aubio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7a2rv5h9-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-jtybangf/aubio/
```

**Comment by PostsDesert** [comment]
Installing from git with the command `pip3 install git+https://github.com/aubio/aubio.git/ -v --user` does work and fixes the original issue. Do you have any idea on why the other won't build? Thanks so much for your help, Griffith.

**Comment by piem** [comment]
Thanks for the info @PostsDesert. It seems you were hit by the same issue as in #84, where distutils would try to build against a previous version of libaubio installed system-wise. This should be fixed now.

**Comment by PostsDesert** [comment]
Awesome to know. Thanks again for the help, Griffith
